### ISSUE TITLE
Decompression when requesting NuGet's `index.json` file causes unhandled error / failure

### ISSUE THREAD

**Issue by molotskya** [microsoft/security-devops-azdevops-task-lib#13]
We noticed that our Azure Pipeline's `Microsoft Security DevOps` task was updated to v1.7.1 (from v1.6.0) between yesterday and today and started seeing an error as demonstrated in the following pictures (the first of which without verbose / debug logging, the second of which with the logging):

![image](https://github.com/microsoft/security-devops-azdevops-task-lib/assets/25205005/71617d9c-3625-4aa2-8b87-70f759b0a8a8)
---
![image](https://github.com/microsoft/security-devops-azdevops-task-lib/assets/25205005/f0e49a02-92a2-4d7a-a5a9-4c14a8c7b73e)
---

Furthermore, if we remove the [linked lines](https://github.com/microsoft/security-devops-azdevops-task-lib/blob/69f9d6cc1b4a3eca65db7277ef8f4b2770bdf234/src/msdo-nuget-client.ts#L535-L536) (the ones handling decompression of the `index.json` from NuGet), the task proceeds properly (installing the CLI successfully).

I can provide more information if you'd (like agent information, what we're calling in our pipeline, etc.), but figured we'd want to get the ball rolling here (since the code is pretty new and we're unsure how different environments / agents will handle the problem)!

**Comment by davidknise** [comment]
Hey @molotskya, thanks for reporting this and with so much detail.

I'm surprised to see it succeeds without the decompression. That line that's failing is a dynamic import, so my initial suspicion is that it's only working in the Node16 build task environment, while the task also specifies Node10 and Node.

I'm going to:
1) Catch failures on the promise of the dynamic import and swallow the exception to allow it to continue with an attempt.
2) Look into node version awareness and see if there's another way to import that ESM module from CommonJS.

Thanks again!

**Comment by davidknise** [comment]
I was able to reproduce this issue on Node10.

Another remediation would be to upgrade the build agent to a version with node16 in the externals, but a fix will be shipped for prior versions of node asap.

Here are the latest agents:
Windows: https://vstsagentpackage.azureedge.net/agent/3.220.5/vsts-agent-win-x64-3.220.5.zip
Linux: https://vstsagentpackage.azureedge.net/agent/3.220.5/vsts-agent-linux-x64-3.220.5.tar.gz

**Comment by molotskya** [comment]
Hey @davidknise,

Thanks for getting back to my issue and detailing what you're seeing on your side - totally checks out that the dynamic import wouldn't work on Node 10 environments but would on Node 16 ones (hence why removing those two lines would allow it to work, plus that aligns with the error messages being bubbled up from Node)!

Honestly surprised that it worked without the decompression too, but not going to question it (especially since the change unblocked our security scans) - we're honestly in the process of moving away from the _old_ build agent that has the issue (moving to a more streamlined approach with a scale set and / or images, such that upgrading the agent will be trivial / a non-issue), but really great to know that there's paths forward for fixing the problem (either upgrading the agent or awaiting the fix).

Thanks again, we really appreciate all the work you've done on this / continue to do! If there's anything else you need from my side, would be happy to help out.

**Comment by davidknise** [comment]
Thanks for your patience @molotskya.

I've deployed version 1.7.2 with backwards compatibility.

This was a big update that allows us to break the dependency on dotnet.
